export default [
  {
    'brand': 'iPhone',
    'model': 'iPhone7,1',
    'platform': 'iOS',
    'system': '15.0',
    'remark': 'iPhone 6 Plus 模拟器',
  },
  {
    'brand': 'iPhone',
    'model': 'iPhone10,1',
    'platform': 'iOS',
    'system': '15.0',
    'remark': 'iPhone 8 模拟器',
  },
  {
    'brand': 'iPhone',
    'model': 'iphone15,2',
    'platform': 'iOS',
    'system': '15.0',
    'remark': 'iPhone 14 Pro 模拟器',
  },
  {
    'brand': 'iPhone',
    'model': 'iphone15,4',
    'platform': 'iOS',
    'system': '15.0',
    'remark': 'iPhone 15 模拟器',
  },
  {
    'brand': 'Huawei',
    'model': 'Huawei Mate 20 Pro',
    'platform': 'Android',
    'system': '9',
    'performance': 'high',
    'remark': '华为 Mate 20 Pro 模拟器',
  },
  {
    'brand': 'Huawei',
    'model': 'Huawei P40 Pro Plus',
    'platform': 'Android',
    'system': '9',
    'performance': 'high',
    'remark': '华为 P40 Pro+ 模拟器',
  },
  {
    'brand': 'Xiaomi',
    'model': 'Xiaomi Readmi K30 5G',
    'platform': 'Android',
    'system': '9',
    'performance': 'high',
    'remark': '红米 K30 Pro 模拟器',
  },
  {
    'brand': 'Xiaomi',
    'model': 'Xiaomi Mi 10 Pro',
    'platform': 'Android',
    'system': '9',
    'performance': 'high',
    'remark': '小米 10 Pro 模拟器',
  },
  {
    'brand': 'Google',
    'model': 'Pixel 6',
    'platform': 'Android',
    'system': '9',
    'performance': 'high',
    'remark': 'Pixel 6 模拟器',
  },
  {
    'brand': 'iPhone',
    'deviceOrientation': 'portrait',
    'model': 'iPhone10,1',
    'platform': 'iOS',
    'system': '13.6',
    'remark': 'iPhone 8',
  },
  {
    'brand': 'iPhone',
    'model': 'iPhone12,8',
    'platform': 'iOS',
    'system': '16.4.1',
    'remark': 'iPhone SE2 真机',
  },
  {
    'brand': 'iPhone',
    'deviceOrientation': 'portrait',
    'model': 'iPhone14,5',
    'platform': 'iOS',
    'system': '16.6',
    'remark': 'iPhone 13',
  },
  {
    'brand': 'iPhone',
    'deviceOrientation': 'portrait',
    'model': 'iPhone15,2',
    'platform': 'iOS',
    'system': '16.4',
    'remark': 'iPhone 14 Pro',
  },
  {
    'brand': 'HUAWEI',
    'deviceOrientation': 'unknown',
    'model': 'HUAWEI LIO-AL00',
    'performance': 'high',
    'platform': 'Android',
    'system': '10',
    'remark': '华为 Mate 30 Pro',
  },
  {
    'brand': 'HUAWEI',
    'deviceOrientation': 'portrait',
    'model': 'HUAWEI DCO-AL00',
    'performance': 'high',
    'platform': 'Android',
    'system': '12',
    'remark': '华为 Mate 50 Pro',
  },
  {
    'brand': 'HUAWEI',
    'deviceOrientation': 'portrait',
    'model': 'HUAWEI ANA-AN00',
    'performance': 'high',
    'platform': 'Android',
    'system': '12',
    'remark': '华为 P40',
  },
  {
    'brand': 'HONOR',
    'deviceOrientation': 'portrait',
    'model': 'HUAWEI CDY-AN90',
    'performance': 'high',
    'platform': 'Android',
    'system': '10',
    'remark': '华为 HONOR 30S',
  },
  {
    'brand': 'samsung',
    'deviceOrientation': 'portrait',
    'model': 'samsung SM-S9210',
    'performance': 'high',
    'platform': 'Android',
    'system': '14',
    'remark': 'samsung SM-S9210',
  },
  {
    'brand': 'vivo',
    'deviceOrientation': 'portrait',
    'model': 'vivo V1924A',
    'performance': 'high',
    'platform': 'Android',
    'system': '10',
    'remark': 'vivo NEX 3 5G',
  },
  {
    'brand': 'vivo',
    'deviceOrientation': 'portrait',
    'model': 'vivo V2203A',
    'performance': 'high',
    'platform': 'Android',
    'system': '12',
    'remark': 'vivo V2203A',
  },
  {
    'brand': 'vivo',
    'deviceOrientation': 'portrait',
    'model': 'vivo V1916A',
    'performance': 'high',
    'platform': 'Android',
    'system': '11',
    'remark': 'VIVO iQOO Pro',
  },
  {
    'platform': 'Android',
    'system': '8.1.0',
    'brand': 'OPPO',
    'model': 'OPPO PBAM00',
    'performance': 'low',
    'remark': 'OPPO A5',
  },
  {
    'brand': 'Xiaomi',
    'deviceOrientation': 'portrait',
    'model': 'Xiaomi Mi9 Pro 5G',
    'performance': 'high',
    'platform': 'Android',
    'system': '9',
    'remark': '小米9 Pro 5G',
  },
  {
    'brand': 'Xiaomi',
    'deviceOrientation': 'portrait',
    'model': 'Xiaomi 23116PN5BC',
    'performance': 'high',
    'platform': 'Android',
    'system': '14',
    'remark': '小米 14 Pro',
  },
  {
    'brand': 'Redmi',
    'deviceOrientation': 'portrait',
    'model': 'Xiaomi 220233L2C',
    'performance': 'middle',
    'platform': 'Android',
    'system': '11',
    'remark': '红米10A',
  },
];
