export default [
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'Windows', 'system':'Windows 10.0', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'Nexus 5', 'system':'Android 5.0', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'Nexus 6', 'system':'Android 5.0', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'Mac 21-inch and above', 'system':'macOS 10.14.3', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPad', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 5', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 6/7/8', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 6/7/8 Plus', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone X', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone XR', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone XS Max', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 12/13 mini', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 12/13 (Pro)', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 12/13 Pro Max', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 14 Pro Max', 'system':'iOS 10.0.1', 'platform':'devtools' },
  { 'benchmarkLevel':-1, 'brand':'devtools', 'memorySize':2048, 'model':'iPhone 15 Pro Max', 'system':'iOS 10.0.1', 'platform':'devtools' },

  {
    'memorySize': 2973,
    'system': 'iOS 16.4.1',
    'model': 'iPhone 8 Plus (GSM+CDMA)<iPhone10,2>',
    'benchmarkLevel': 28,
    'brand': 'iPhone',
    'platform': 'ios',
  },
  {
    'benchmarkLevel': -1,
    'brand': 'iPhone',
    'memorySize': 2959,
    'model': 'iPhone SE (2nd generation)<iPhone12,8>',
    'platform': 'ios',
    'system': 'iOS 16.4.1',
  },
  {
    'memorySize': 5695,
    'system': 'iOS 16.3',
    'model': 'iPhone 14<iPhone14,7>',
    'benchmarkLevel': -1,
    'brand': 'iPhone',
    'platform': 'ios',
  },
  {
    'benchmarkLevel': -1,
    'brand': 'iPhone',
    'memorySize': 5650,
    'model': 'iPhone 14 pro<iPhone15,2>',
    'platform': 'ios',
    'system': 'iOS 17.3.1',
  },
  {
    'benchmarkLevel': -1,
    'brand': 'iPhone',
    'memorySize': 7675,
    'model': 'iPhone 15 pro<iPhone16,1>',
    'platform': 'ios',
    'system': 'iOS 17.3.1',
  },

  {
    'benchmarkLevel': 35,
    'cpuType': 'unknown',
    'system': 'Android 12',
    'memorySize': 7322,
    'model': 'CET-AL00',
    'brand': 'HUAWEI',
    'platform': 'android',
    'remark': '华为Mate 50',
  },
  {
    'benchmarkLevel': 29,
    'cpuType': 'unknown',
    'system': 'Android 12',
    'memorySize': 15601,
    'model': 'ALN-AL10',
    'brand': 'HUAWEI',
    'platform': 'android',
    'remark': '华为Mate60 Pro+',
  },
  {
    'benchmarkLevel': 31,
    'cpuType': 'unknown',
    'system': 'Android 14',
    'memorySize': 7215,
    'model': '23127PN0CC',
    'brand': 'Xiaomi',
    'platform': 'android',
    'remark': '小米14',
  },
  {
    'benchmarkLevel': 6,
    'cpuType': 'MT6762G',
    'system': 'Android 11',
    'memorySize': 3779,
    'model': '220233L2C',
    'brand': 'Redmi',
    'platform': 'android',
    'remark': '红米 10A',
  },
  {
    'benchmarkLevel': 34,
    'brand': 'OPPO',
    'memorySize': 7195,
    'model': '2201123C',
    'platform': 'android',
    'system': 'Android 12',
  },
  {
    'benchmarkLevel': 21,
    'brand': 'OPPO',
    'memorySize': 5621,
    'model': 'PBEM00',
    'platform': 'android',
    'system': 'Android 10',
  },

];
