name: Bug report
description: Submit issues to help us improve Galacean Effects
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Welcome to report any issues you encounter while using Galacean Effects. Our team will respond actively.

        Before submitting an issue, reviewing the following resources could save you time and might help you find an existing related issue:

        * [User Guide](https://galacean.antgroup.com/effects/user/user-doc) — Understand the basics of the GalaceanEffects editor
        * [Developer Guide](https://galacean.antgroup.com/effects/user/dev-doc) — Guidance on using Galacean Effects Runtime
        * [API Reference](https://galacean.antgroup.com/effects/api) — Detailed API documentation
        * [FAQs](https://galacean.antgroup.com/effects/user/gasrv4ka5sacrwpg) — Compilation of frequently asked questions
        * [Changelog](https://galacean.antgroup.com/effects/user/changelog) — Includes bug fixes and new features of Runtime updates

        Additionally, you can quickly view or respond to related issues through keyword searches in the Issue area.

        When creating an issue, please provide as much detailed information as possible to help us locate and fix the problem quickly and to facilitate others in searching. Thank you for your cooperation! 🥰

  - type: textarea
    id: search_terms
    attributes:
      label: 🔎 Search Terms
      description: What search terms did you use when trying to find an existing issue report?
      placeholder: |
        - keyframe
        - downgrade image
        - spine
        - 3D Model
        - ...
    validations:
      required: true

  - type: input
    id: version_info
    attributes:
      label: 🕗 Version Info
      description: What is the version of Galacean Effects you are using?
    validations:
      required: true

  - type: checkboxes
    id: platform_info
    attributes:
      label: 🖥️ Platform Information
      description: On which platform(s) did you experience the issue?
      options:
        - label: iOS
        - label: Android
        - label: Web
        - label: Mini Program (Alipay/WeChat)
        - label: WeChat Mini Game
        - label: macOS
        - label: Windows
        - label: Linux
        - label: Other
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: 💻 Code Sample
      description: |
        Please post the relevant code sample here.

        We can address your report more quickly if:

          - The code sample is concise and clear.
          - It does not rely on external libraries.
          - A comparison or workaround is provided.

        Reports may be slower to investigate if:
          - There is too much extraneous code.
          - We need to clone a large repo and verify that the issue lies elsewhere.
          - The sample is confusing or doesn't clearly demonstrate the issue.

      value: |
        ```
        // Your code here
        ```

  - type: textarea
    id: expected_behavior
    attributes:
      label: 🙂 Expected Behavior
      placeholder: What actually happened, and why is it problematic?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 🙁 Actual Behavior
      placeholder: What did you expect to happen instead, and why?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: ⏯ Steps to Reproduce
      description: Please provide a minimal code sample that reproduces the issue, or a link to a repo that does so.
      placeholder: |
        1. Click on '....'
        2. Other actions ...
        3. See the error
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information about the Issue
