/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AGUIAccordion: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/accordion/AGUIAccordion.vue')['default']
    AGUIAccordionItem: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/accordion/AGUIAccordionItem.vue')['default']
    AGUIApp: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIApp.vue')['default']
    AGUIAssetsExplorer: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/explorer/AGUIAssetsExplorer.vue')['default']
    AGUIBreadcrumb: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/breadcrumb/AGUIBreadcrumb.vue')['default']
    AGUIButton: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/button/AGUIButton.vue')['default']
    AGUICheckbox: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUICheckbox.vue')['default']
    AGUIColorPicker: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIColorPicker.vue')['default']
    AGUIContextMenu: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/context-menu/AGUIContextMenu.vue')['default']
    AGUIContextMenuItem: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/context-menu/AGUIContextMenuItem.vue')['default']
    AGUIDetails: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIDetails.vue')['default']
    AGUIExplorerControls: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/explorer/AGUIExplorerControls.vue')['default']
    AGUIFileItem: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/explorer/AGUIFileItem.vue')['default']
    AGUIFileList: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/explorer/AGUIFileList.vue')['default']
    AGUIForm: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/form/AGUIForm.vue')['default']
    AGUIFormItem: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/form/AGUIFormItem.vue')['default']
    AGUIHr: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/common/AGUIHr.vue')['default']
    AGUIIcon: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/button/AGUIIcon.vue')['default']
    AGUIIconButton: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/button/AGUIIconButton.vue')['default']
    AGUIInput: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIInput.vue')['default']
    AGUIInputNumber: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIInputNumber.vue')['default']
    AGUIInputVector: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIInputVector.vue')['default']
    AGUILayout: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/layout/AGUILayout.vue')['default']
    AGUIMenubar: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/menu/AGUIMenubar.vue')['default']
    AGUIMenuBar: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.8_vue@3.4.10/node_modules/@advjs/gui/client/components/menu/AGUIMenuBar.vue')['default']
    AGUIMenubarMenu: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/menu/AGUIMenubarMenu.vue')['default']
    AGUINumberField: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUINumberField.vue')['default']
    AGUINumberSlider: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUINumberSlider.vue')['default']
    AGUIOpenDirectory: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/explorer/AGUIOpenDirectory.vue')['default']
    AGUIOverlay: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIOverlay.vue')['default']
    AGUIPanel: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIPanel.vue')['default']
    AGUIPropertiesPanel: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/panel/AGUIPropertiesPanel.vue')['default']
    AGUIProperty: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUIProperty.vue')['default']
    AGUISelect: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/select/AGUISelect.vue')['default']
    AGUISelectOption: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.4_vue@3.4.7/node_modules/@advjs/gui/client/components/select/AGUISelectOption.vue')['default']
    AGUISlider: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/AGUISlider.vue')['default']
    AGUITabPanel: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/tabs/AGUITabPanel.vue')['default']
    AGUITabs: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/tabs/AGUITabs.vue')['default']
    AGUITree: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/tree/AGUITree.vue')['default']
    AGUITreeNode: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/tree/AGUITreeNode.vue')['default']
    BIconChevronLeft: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/icons/BIconChevronLeft.vue')['default']
    BIconChevronRight: typeof import('./../../node_modules/.pnpm/@advjs+gui@0.0.3-beta.13_vue@3.4.10/node_modules/@advjs/gui/client/components/icons/BIconChevronRight.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PanelHierarchy: typeof import('./src/components/PanelHierarchy.vue')['default']
    PanelProject: typeof import('./src/components/PanelProject.vue')['default']
    PanelScene: typeof import('./src/components/PanelScene.vue')['default']
  }
}
