import './camera.spec';
import './graph.spec';
//import './load-tex.spec';
//import './load.spec';
//import './on-end.spec';
import './order.spec';
import './plugin.spec';
import './raycast.spec';
import './comp-vfx-item.spec';
